//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleXL {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleXL.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;borders count=&quot;2&quot;&gt;
        ///  &lt;border&gt;
        ///    &lt;left/&gt;
        ///    &lt;right/&gt;
        ///    &lt;top/&gt;
        ///    &lt;bottom/&gt;
        ///    &lt;diagonal/&gt;
        ///  &lt;/border&gt;
        ///  &lt;border&gt;
        ///    &lt;left style=&quot;thin&quot;&gt;
        ///      &lt;color indexed=&quot;64&quot;/&gt;
        ///    &lt;/left&gt;
        ///    &lt;right style=&quot;thin&quot;&gt;
        ///      &lt;color indexed=&quot;64&quot;/&gt;
        ///    &lt;/right&gt;
        ///    &lt;top style=&quot;thin&quot;&gt;
        ///      &lt;color indexed=&quot;64&quot;/&gt;
        ///    &lt;/top&gt;
        ///    &lt;bottom style=&quot;thin&quot;&gt;
        ///      &lt;color indexed=&quot;64&quot;/&gt;
        ///    &lt;/bottom&gt;
        ///    &lt;diagonal/&gt;
        ///  &lt;/border&gt;
        ///&lt;/borders&gt;.
        /// </summary>
        internal static string styles_borders {
            get {
                return ResourceManager.GetString("styles_borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fonts count=&quot;3&quot; x14ac:knownFonts=&quot;1&quot;&gt;
        ///  &lt;font&gt;
        ///    &lt;sz val=&quot;11&quot;/&gt;
        ///    &lt;color theme=&quot;1&quot;/&gt;
        ///    &lt;name val=&quot;Calibri&quot;/&gt;
        ///    &lt;family val=&quot;2&quot;/&gt;
        ///    &lt;scheme val=&quot;minor&quot;/&gt;
        ///  &lt;/font&gt;
        ///  &lt;font&gt;
        ///    &lt;b/&gt;
        ///    &lt;sz val=&quot;11&quot;/&gt;
        ///    &lt;color theme=&quot;1&quot;/&gt;
        ///    &lt;name val=&quot;Calibri&quot;/&gt;
        ///    &lt;family val=&quot;2&quot;/&gt;
        ///    &lt;scheme val=&quot;minor&quot;/&gt;
        ///  &lt;/font&gt;
        ///  &lt;font&gt;
        ///    &lt;i/&gt;
        ///    &lt;sz val=&quot;11&quot;/&gt;
        ///    &lt;color theme=&quot;1&quot;/&gt;
        ///    &lt;name val=&quot;Calibri&quot;/&gt;
        ///    &lt;family val=&quot;2&quot;/&gt;
        ///    &lt;scheme val=&quot;minor&quot;/&gt;
        ///  &lt;/font&gt;
        ///&lt;/fonts&gt;.
        /// </summary>
        internal static string styles_fonts {
            get {
                return ResourceManager.GetString("styles_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Types xmlns=&quot;http://schemas.openxmlformats.org/package/2006/content-types&quot;&gt;&lt;Default Extension=&quot;rels&quot; ContentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot;/&gt;&lt;Default Extension=&quot;xml&quot; ContentType=&quot;application/xml&quot;/&gt;&lt;Override PartName=&quot;/xl/workbook.xml&quot; ContentType=&quot;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml&quot;/&gt;&lt;Override PartName=&quot;/xl/worksheets/sheet1.xml&quot; ContentType=&quot;application/vnd.openxmlformats-office [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_Content_Types_ {
            get {
                return ResourceManager.GetString("Template_Content_Types_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Properties xmlns=&quot;http://schemas.openxmlformats.org/officeDocument/2006/extended-properties&quot; xmlns:vt=&quot;http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes&quot;&gt;&lt;Application&gt;Microsoft Excel&lt;/Application&gt;&lt;DocSecurity&gt;0&lt;/DocSecurity&gt;&lt;ScaleCrop&gt;false&lt;/ScaleCrop&gt;&lt;HeadingPairs&gt;&lt;vt:vector size=&quot;2&quot; baseType=&quot;variant&quot;&gt;&lt;vt:variant&gt;&lt;vt:lpstr&gt;Worksheets&lt;/vt:lpstr&gt;&lt;/vt:variant&gt;&lt;vt:variant&gt;&lt;vt:i4&gt;1&lt;/vt:i4&gt;&lt;/vt:variant&gt;&lt;/vt:vector&gt;&lt;/HeadingPairs&gt;&lt;Title [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_docProps_app {
            get {
                return ResourceManager.GetString("Template_docProps_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;cp:coreProperties xmlns:cp=&quot;http://schemas.openxmlformats.org/package/2006/metadata/core-properties&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; xmlns:dcmitype=&quot;http://purl.org/dc/dcmitype/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;dc:creator&gt;Mateus&lt;/dc:creator&gt;&lt;cp:lastModifiedBy&gt;Mateus&lt;/cp:lastModifiedBy&gt;&lt;dcterms:created xsi:type=&quot;dcterms:W3CDTF&quot;&gt;2017-06-11T18:27:03Z&lt;/dcterms:created&gt;&lt;dcterms:m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_docProps_core {
            get {
                return ResourceManager.GetString("Template_docProps_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties&quot; Target=&quot;docProps/core.xml&quot;/&gt;&lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_rels_rels {
            get {
                return ResourceManager.GetString("Template_rels_rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles&quot; Target=&quot;styles.xml&quot;/&gt;&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme&quot; Target=&quot;theme/theme1.xml&quot;/&gt;&lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet&quot; Tar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_xl_rels_workbook {
            get {
                return ResourceManager.GetString("Template_xl_rels_workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;a:theme xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; name=&quot;Office Theme&quot;&gt;&lt;a:themeElements&gt;&lt;a:clrScheme name=&quot;Office&quot;&gt;&lt;a:dk1&gt;&lt;a:sysClr val=&quot;windowText&quot; lastClr=&quot;000000&quot;/&gt;&lt;/a:dk1&gt;&lt;a:lt1&gt;&lt;a:sysClr val=&quot;window&quot; lastClr=&quot;FFFFFF&quot;/&gt;&lt;/a:lt1&gt;&lt;a:dk2&gt;&lt;a:srgbClr val=&quot;44546A&quot;/&gt;&lt;/a:dk2&gt;&lt;a:lt2&gt;&lt;a:srgbClr val=&quot;E7E6E6&quot;/&gt;&lt;/a:lt2&gt;&lt;a:accent1&gt;&lt;a:srgbClr val=&quot;4472C4&quot;/&gt;&lt;/a:accent1&gt;&lt;a:accent2&gt;&lt;a:srgbClr val=&quot;ED7D31&quot;/&gt;&lt;/a:accent2&gt;&lt;a:accent3&gt;&lt;a:srgbClr val= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_xl_theme_theme1 {
            get {
                return ResourceManager.GetString("Template_xl_theme_theme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;workbook xmlns=&quot;http://schemas.openxmlformats.org/spreadsheetml/2006/main&quot; xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;x15&quot; xmlns:x15=&quot;http://schemas.microsoft.com/office/spreadsheetml/2010/11/main&quot;&gt;&lt;fileVersion appName=&quot;xl&quot; lastEdited=&quot;7&quot; lowestEdited=&quot;7&quot; rupBuild=&quot;18067&quot;/&gt;&lt;workbookPr defaultThemeVersion=&quot;166925&quot;/&gt;&lt;mc:AlternateConte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_xl_workbook {
            get {
                return ResourceManager.GetString("Template_xl_workbook", resourceCulture);
            }
        }
    }
}
